apiVersion: apps/v1
kind: Deployment
metadata:
  name: devboard-worker
  labels: { app: devboard-worker }
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels: { app: devboard-worker }
  template:
    metadata:
      labels: { app: devboard-worker }
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.registry }}/devboard-api:{{ .Values.image.apiTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npm", "run", "worker"]
          envFrom:
            - secretRef: { name: {{ .Values.secrets.existingSecretName }} }
          env:
            - name: DEVBOARD_MODE
              value: {{ .Values.mode }}
            - name: ANALYZER_URL
              value: "http://devboard-analyzer:{{ .Values.analyzer.port }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.postgres.enabled }}devboard-postgres{{ else }}{{ .Values.postgres.externalConnectionSecretName }}{{ end }}
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.redis.enabled }}devboard-redis{{ else }}{{ .Values.redis.externalConnectionSecretName }}{{ end }}
                  key: REDIS_URL
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
