// @devboard/shared — centralized error codes so api/analyzer/cli log consistently.

export const ErrorCodes = {
  WEBHOOK_SIGNATURE_INVALID: "E_WEBHOOK_SIGNATURE_INVALID",
  WEBHOOK_PAYLOAD_MALFORMED: "E_WEBHOOK_PAYLOAD_MALFORMED",
  GITHUB_TOKEN_FETCH_FAILED: "E_GITHUB_TOKEN_FETCH_FAILED",
  GITHUB_RATE_LIMITED: "E_GITHUB_RATE_LIMITED",
  ANALYZER_TIMEOUT: "E_ANALYZER_TIMEOUT",
  ANALYZER_UNREACHABLE: "E_ANALYZER_UNREACHABLE",
  LLM_TIMEOUT: "E_LLM_TIMEOUT",
  LLM_MALFORMED_JSON: "E_LLM_MALFORMED_JSON",
  OSV_API_UNAVAILABLE: "E_OSV_API_UNAVAILABLE",
  POLICY_CONFIG_PARSE_FAILED: "E_POLICY_CONFIG_PARSE_FAILED",
  PLUGIN_TIMEOUT: "E_PLUGIN_TIMEOUT",
  PLUGIN_FAILED: "E_PLUGIN_FAILED",
  JOB_FAILED_FINAL: "E_JOB_FAILED_FINAL",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
